# Generated by Django 4.2.3 on 2023-08-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_order_address_alter_order_full_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="full_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="orderdetail",
            old_name="orderdetail_count",
            new_name="quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_amout",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="strip_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
