# Generated by Django 4.2.3 on 2023-08-14 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_rename_full_name_order_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="strip_token",
            new_name="stripe_token",
        ),
    ]
