# Generated by Django 4.2.3 on 2023-08-14 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_rename_strip_token_order_stripe_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="paid_amout",
            new_name="paid_amount",
        ),
    ]
