# Generated by Django 4.2.3 on 2023-08-14 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0009_alter_book_category"),
        ("cart", "0005_rename_paid_amout_order_paid_amount"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderDetail",
            new_name="OrderItem",
        ),
    ]
