# Generated by Django 4.2.3 on 2023-07-18 19:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_book_book_language_book_published_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="info",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
