# Generated by Django 4.2.3 on 2023-07-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_alter_book_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(null=True, verbose_name="توضیح کوتاه"),
        ),
    ]
