# Generated by Django 4.2.3 on 2023-08-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0005_rename_book_count_book_cover_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="thumbnmail",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
