# Generated by Django 4.2.3 on 2023-08-03 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0006_book_slug_book_thumbnmail_category_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="thumbnmail",
            new_name="thumbnail",
        ),
    ]
